version: "3.9"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: app
    depends_on:
      - mongodb
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      python scripts/01_get_image_data.py
      "

volumes:
  mongo_data: